# Generated by Django 2.2 on 2020-06-20 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'managed': True},
        ),
    ]
