# Generated by Django 2.2 on 2020-06-20 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0002_auto_20200620_1028'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'managed': False},
        ),
    ]
